/*
   CP4 - Cognitive Data Science + Machine Learning & Modelling
   Parte 1: estrutura Oracle para o dataset Case iFood.

   Este script nao remove tabelas existentes. Se precisar refazer a tabela,
   execute manualmente, depois de confirmar o nome/schema:

       DROP TABLE IFOOD_CUSTOMERS PURGE;
*/

CREATE TABLE IFOOD_CUSTOMERS (
    ID                   NUMBER(6)       NOT NULL,
    YEAR_BIRTH           NUMBER(4)       NOT NULL,
    EDUCATION            VARCHAR2(20)    NOT NULL,
    MARITAL_STATUS       VARCHAR2(20)    NOT NULL,
    INCOME               NUMBER(10,2),
    KIDHOME              NUMBER(1)       NOT NULL,
    TEENHOME             NUMBER(1)       NOT NULL,
    DT_CUSTOMER          DATE            NOT NULL,
    RECENCY              NUMBER(2)       NOT NULL,
    MNTWINES             NUMBER(8)       NOT NULL,
    MNTFRUITS            NUMBER(8)       NOT NULL,
    MNTMEATPRODUCTS      NUMBER(8)       NOT NULL,
    MNTFISHPRODUCTS      NUMBER(8)       NOT NULL,
    MNTSWEETPRODUCTS     NUMBER(8)       NOT NULL,
    MNTGOLDPRODS         NUMBER(8)       NOT NULL,
    NUMDEALSPURCHASES    NUMBER(2)       NOT NULL,
    NUMWEBPURCHASES      NUMBER(2)       NOT NULL,
    NUMCATALOGPURCHASES  NUMBER(2)       NOT NULL,
    NUMSTOREPURCHASES    NUMBER(2)       NOT NULL,
    NUMWEBVISITSMONTH    NUMBER(2)       NOT NULL,
    ACCEPTEDCMP3         NUMBER(1)       NOT NULL,
    ACCEPTEDCMP4         NUMBER(1)       NOT NULL,
    ACCEPTEDCMP5         NUMBER(1)       NOT NULL,
    ACCEPTEDCMP1         NUMBER(1)       NOT NULL,
    ACCEPTEDCMP2         NUMBER(1)       NOT NULL,
    COMPLAIN             NUMBER(1)       NOT NULL,
    Z_COSTCONTACT        NUMBER(2)       NOT NULL,
    Z_REVENUE            NUMBER(2)       NOT NULL,
    RESPONSE             NUMBER(1)       NOT NULL
);

ALTER TABLE IFOOD_CUSTOMERS ADD CONSTRAINT IFOOD_CUSTOMERS_PK
    PRIMARY KEY (ID);

ALTER TABLE IFOOD_CUSTOMERS ADD CONSTRAINT IFOOD_CUSTOMERS_CHILDREN_CK
    CHECK (KIDHOME BETWEEN 0 AND 2 AND TEENHOME BETWEEN 0 AND 2);

ALTER TABLE IFOOD_CUSTOMERS ADD CONSTRAINT IFOOD_CUSTOMERS_RECENCY_CK
    CHECK (RECENCY BETWEEN 0 AND 99);

ALTER TABLE IFOOD_CUSTOMERS ADD CONSTRAINT IFOOD_CUSTOMERS_BINARY_CK
    CHECK (
        ACCEPTEDCMP1 IN (0, 1) AND ACCEPTEDCMP2 IN (0, 1)
        AND ACCEPTEDCMP3 IN (0, 1) AND ACCEPTEDCMP4 IN (0, 1)
        AND ACCEPTEDCMP5 IN (0, 1) AND COMPLAIN IN (0, 1)
        AND RESPONSE IN (0, 1)
    );

ALTER TABLE IFOOD_CUSTOMERS ADD CONSTRAINT IFOOD_CUSTOMERS_MONEY_CK
    CHECK (
        INCOME IS NULL OR INCOME >= 0
    );

ALTER TABLE IFOOD_CUSTOMERS ADD CONSTRAINT IFOOD_CUSTOMERS_CONSTANTS_CK
    CHECK (Z_COSTCONTACT = 3 AND Z_REVENUE = 11);

COMMENT ON TABLE IFOOD_CUSTOMERS IS
    'Case iFood - Customer Personality Analysis para o CP4';

COMMENT ON COLUMN IFOOD_CUSTOMERS.RESPONSE IS
    'Alvo: resposta positiva a campanha';

