/* CP4 - validacao da carga e demonstracao controlada de DDL/DML */

SELECT COUNT(*) AS TOTAL_REGISTROS
FROM IFOOD_CUSTOMERS;

SELECT COUNT(*) AS TOTAL_IDS_DISTINTOS
FROM (SELECT DISTINCT ID FROM IFOOD_CUSTOMERS);

SELECT RESPONSE, COUNT(*) AS QUANTIDADE,
       ROUND(100 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS PERCENTUAL
FROM IFOOD_CUSTOMERS
GROUP BY RESPONSE
ORDER BY RESPONSE;

SELECT COUNT(*) AS INCOME_NULO
FROM IFOOD_CUSTOMERS
WHERE INCOME IS NULL;

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION,
       DATA_SCALE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'IFOOD_CUSTOMERS'
ORDER BY COLUMN_ID;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'IFOOD_CUSTOMERS'
ORDER BY CONSTRAINT_NAME;

/*
   DML isolado. A tabela de demonstracao evita alterar o dataset do trabalho.
   O script mostra CREATE, ALTER, INSERT, UPDATE e DELETE.
*/
CREATE TABLE IFOOD_CP4_DML_DEMO (
    DEMO_ID NUMBER(6) NOT NULL,
    LABEL   VARCHAR2(40) NOT NULL,
    AMOUNT  NUMBER(10,2)
);

ALTER TABLE IFOOD_CP4_DML_DEMO ADD CONSTRAINT IFOOD_CP4_DML_DEMO_PK
    PRIMARY KEY (DEMO_ID);

INSERT INTO IFOOD_CP4_DML_DEMO (DEMO_ID, LABEL, AMOUNT)
VALUES (1, 'registro de teste', 100);

UPDATE IFOOD_CP4_DML_DEMO
SET AMOUNT = AMOUNT + 25
WHERE DEMO_ID = 1;

DELETE FROM IFOOD_CP4_DML_DEMO
WHERE DEMO_ID = 1;

COMMIT;

DROP TABLE IFOOD_CP4_DML_DEMO PURGE;
