/* Query-base solicitada no enunciado para o DataFrame de ML. */

SELECT
    ID,
    YEAR_BIRTH,
    EDUCATION,
    MARITAL_STATUS,
    INCOME,
    KIDHOME,
    TEENHOME,
    DT_CUSTOMER,
    RECENCY,
    MNTWINES,
    MNTFRUITS,
    MNTMEATPRODUCTS,
    MNTFISHPRODUCTS,
    MNTSWEETPRODUCTS,
    MNTGOLDPRODS,
    NUMDEALSPURCHASES,
    NUMWEBPURCHASES,
    NUMCATALOGPURCHASES,
    NUMSTOREPURCHASES,
    NUMWEBVISITSMONTH,
    ACCEPTEDCMP3,
    ACCEPTEDCMP4,
    ACCEPTEDCMP5,
    ACCEPTEDCMP1,
    ACCEPTEDCMP2,
    COMPLAIN,
    Z_COSTCONTACT,
    Z_REVENUE,
    RESPONSE
FROM IFOOD_CUSTOMERS
ORDER BY ID;

